Создал fetch.js для работы с сервером
htmlacademy-javascript/1530953-keksobooking-23 pull request #10
Opened 2021-07-07 13:55 UTC by ks123kirill

2021-07-08 06:57 UTC, 4err requested changes
При ошибке отправки данных форма не должна сбрасываться. Зачем мучить пользователя снова заполнять все с нуля.

2021-07-08 06:57 UTC, 4err commented on js/fetch.js
> +        mapFiltersReset;
Это же не вызовы функций. Здесь ты должен вызвать функцию обработчик, а в параметрах к sendData наоборот написать функции без вызова.

2021-07-08 06:57 UTC, 4err commented on js/form-validation.js
> +    /* Chrome, FireFox не позволяют вводить символы превышающее maxlength="100" в разметке, поэтому эта валидация не показывается на экране */
Ничего страшного, зато, если какой-то умный пользователь удалит аттрибут `maxlength="100"` через инструменты разработчика, валидация все равно сработает. Это перестраховка.

2021-07-08 06:57 UTC, 4err commented on js/form-validation.js
> +    mapFilters.reset(),
Вот тут, когда ты передаешь функции обработчики, тебе нужно их не вызывать, а передавать без круглых скобок. 
Функция `reset` у формы сбрасывает форму к значениям по умолчанию прописанным в HTML коде. 
Также таких сбросов или функций может быть много, не нужно растягивать функцию sendData неопределенным количеством обработчиков. Принято делать один на успех и один на неудачу. 
Соответственно ты в одном этом обработчике можешь вызвать все нужные тебе функции. Тут логика такая же как с обычным addEventListener, но в отличие от него это работа с твоей собственной функцией.

2021-07-08 06:57 UTC, 4err commented on js/form-validation.js
> +  mapFilters.reset(); // Временное решение. Не реализован сброс фильтрации меток, фильтр не работает.
Код написан правильно. Но ты вешаешь этот обработчик на кнопку с типом reset, которая после твоего обработчика запускает сброс формы и сбрасывает все что ты сделал. Чтоб такого не происходило, нужно не забывать добавлять вызов `preventDefault()` чтоб отменить действие элемента по умолчанию.

2021-07-08 06:57 UTC, 4err commented on js/map.js
> +  Особенности работы type="reset"? Также addressInput.value должен был поменять value на 52 строчке - mainMarker.on('moveend', (evt) => { */
Написал выше, ресет за тобой стирает эти изменения.

2021-07-08 06:57 UTC, 4err commented on js/modals.js
> +  // eslint-disable-next-line no-use-before-define
Напоминаю, что правила нельзя использовать

2021-07-08 11:19 UTC, ks123kirill commented on js/form-validation.js
> +    /* Chrome, FireFox не позволяют вводить символы превышающее maxlength="100" в разметке, поэтому эта валидация не показывается на экране */
Ок. Понятно

2021-07-08 12:08 UTC, ks123kirill commented on js/form-validation.js
> +  mapFilters.reset(); // Временное решение. Не реализован сброс фильтрации меток, фильтр не работает.
Ок. Поправил.

2021-07-08 12:08 UTC, ks123kirill commented on js/map.js
> +  Особенности работы type="reset"? Также addressInput.value должен был поменять value на 52 строчке - mainMarker.on('moveend', (evt) => { */
Исправил

2021-07-09 08:36 UTC, ks123kirill commented on js/fetch.js
> +        mapFiltersReset;
Хорошо. Исправил

2021-07-09 08:37 UTC, ks123kirill commented on js/form-validation.js
> +    mapFilters.reset(),
Хорошо. Исправил.

2021-07-09 10:26 UTC, merged