Создал card-filter.js модуль фильтрации меток на карте
htmlacademy-javascript/1530953-keksobooking-23 pull request #11
Opened 2021-07-12 10:23 UTC by ks123kirill

2021-07-12 11:32 UTC, 4err requested changes
https://take.ms/oHQZG

https://take.ms/jnlWJ 
Что-то с фильтрами не то. Выдают некорректные объявления.

2021-07-12 11:32 UTC, 4err commented on js/cards-filter.js
> +}
Вместо отслеживания каждого фильтра, можно ловить событие изменения формы и не плодить функции. 

Также при текущем подходе это также можно заменитьодной функцией, добавив помимо коллбека, параметр, в котором будет содержаться элемент к которому добавляется обработчик.

2021-07-12 11:32 UTC, 4err commented on js/cards-filter.js
> +  }
Тебе ранки тут не очень нужны, т.к. нужно полное соответствие фильтрам, поэтому объявление либо подходит и отображается, либо нет. Никакого ранжирования.

2021-07-12 11:32 UTC, 4err commented on js/cards-filter.js
> +  }
Посмотри на функцию .includes() массивов. 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

Она должна упростить эту проверку. 
Также ты можешь сразу получить только выбранные фичи воспользовавшись псевдоселектором `:checked` в querySelectorе

2021-07-12 11:32 UTC, 4err commented on js/form-validation.js
> +  });
Нет, загружать заново ненужно. Нужно хранить исходный массив в какой-то переменной и обращаться к ней для новых фильтров.

2021-07-12 13:17 UTC, ks123kirill commented on js/cards-filter.js
> +}
OK. Исправил на делегирование событий внутри формы фильтра

2021-07-13 07:36 UTC, ks123kirill commented on js/cards-filter.js
> +  }
Хорошо. Убрал ранжирование

2021-07-13 16:41 UTC, ks123kirill commented on js/form-validation.js
> +  });
Сохранил в массив

2021-07-13 16:42 UTC, ks123kirill commented on js/cards-filter.js
> +  }
Ок. Исправил

2021-07-14 05:34 UTC, 4err requested changes

2021-07-14 05:34 UTC, 4err commented on js/cards-filter.js
> +}
Не очень понятно предназначение этой функции. Почему вместо нее, там, где она используется не вызывать `isCardValid` ? Для чего плодить функции, которые просто вызывают другие функции.

2021-07-14 05:34 UTC, 4err commented on js/cards-filter.js
> +    return counter === array.length;
Можно еще проще. Без счетчика, доп массива. 
Говоря математическим языком мы можем пойти методом от противного. Положим, что элемент нам подходит и обозначим какой-нибудь флаг в состояние true. И теперь достаточно, как только мы находим первый не включенный в массив элемент, возвращать false. Нам достаточно любого отсутствующего элемента, чтобы фильтр не прошел.

2021-07-14 05:34 UTC, 4err commented on js/fetch.js
> +      dataServer.push(ads); // как то можно через функцию, не разобрался.
Зачем push если можно просто присвоить значение? Так у тебя не будет многомерного массива и проблем с ним в дальнейшем. 
Через функцию, внутри обработчика нужно также просто присвоить в экспортированную переменную данные.

2021-07-14 06:18 UTC, 4err commented on js/fetch.js
> +      dataServer.push(ads); // как то можно через функцию, не разобрался.
Присвоить значение нельзя, т.к. у нас запрет на экспорт `let` переменных. Вместо этого можно воспользоваться методом `.flat()`. Он превращает многомерный массив в одномерный.

2021-07-14 06:31 UTC, 4err commented on js/fetch.js
> +      dataServer.push(ads); // как то можно через функцию, не разобрался.
Хотя шило на мыло получается. Пожалуй все же лучше использовать объект с определенным полем. Это будет оптимальным решением.

2021-07-14 07:02 UTC, ks123kirill commented on js/cards-filter.js
> +}
Ок. Исправил.

2021-07-14 08:40 UTC, ks123kirill commented on js/cards-filter.js
> +    return counter === array.length;
Ок. Исправил.

2021-07-14 08:48 UTC, ks123kirill commented on js/fetch.js
> +      dataServer.push(ads); // как то можно через функцию, не разобрался.
Хорошо. Оставляю многомерный массив.

2021-07-14 09:48 UTC, merged