Создал функции со случайными числами
htmlacademy-javascript/1530953-keksobooking-23 pull request #2
Opened 2021-05-29 13:46 UTC by ks123kirill

2021-05-30 05:30 UTC, 4err requested changes

2021-05-30 05:30 UTC, 4err commented on js/main.js
> +function randomInteger(min, max) {
>Учтите, что диапазон может быть только положительный, включая ноль. А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.

Функция работает с любыми данными, данные ограничения никак не обрабатываются. Со второй функцией аналогично.

2021-05-31 05:36 UTC, 4err requested changes

2021-05-31 05:36 UTC, 4err commented on js/main.js
> +}
В текущем варианте функция никак не сообщит об ошибке и пользователь будет думать, что все работает, что приведет к ошибкам. Нужно или выдать исключение с помощью `throw`, либо выдать код ошибки, либо хотя бы просто сообщение. 
Исключение это самый надежный и правильный вариант, но его можно сделать позже.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw

2021-05-31 05:36 UTC, 4err commented on js/main.js
> +    rand < min ? rand = min : rand; // если min = 0 и мах = 0, то при выполнении тернарного оператора с условием rand > max, rand будет отрицательным
Не стоит так использовать тернарные операторы. Это очень сильно запутывает код. Также старайся не использовать оператор присваивания как часть одного из результатов выполнения. Если тебе нужно в зависимости от условия присвоить переменной разные значения можно написать так:
`let test = a > b ? a : b;`
При такой записи в переменную `test` в результате попадет или `a` или `b`

Также, чтоб избавиться от этого условия можно просто запретить указывать 2 одинаковых числа, в этом же нет смысла.

2021-05-31 05:36 UTC, 4err commented on js/main.js
> +    rand > max ? rand -= 1 : rand; // при умножении на Math.random(), rand может становится > max
Вообще такого происходить не должно. Вероятно функция работает не так как надо.
https://take.ms/2dn36
При тестах в случае если задать 2 близких значения, то выдается одно и то же значение, такого точно быть не должно.

2021-05-31 06:53 UTC, ks123kirill commented on js/main.js
> +}
Ок. Сделал сообщение об ошибке. Throw сделаем позже.

2021-05-31 07:05 UTC, ks123kirill commented on js/main.js
> +    rand < min ? rand = min : rand; // если min = 0 и мах = 0, то при выполнении тернарного оператора с условием rand > max, rand будет отрицательным
Ok

2021-05-31 07:51 UTC, ks123kirill commented on js/main.js
> +    rand > max ? rand -= 1 : rand; // при умножении на Math.random(), rand может становится > max
https://prntscr.com/13mh1le    Поправил. Тест проходит.

2021-05-31 08:21 UTC, merged