Создал модуль валидации формы
htmlacademy-javascript/1530953-keksobooking-23 pull request #6
Opened 2021-06-22 08:27 UTC by ks123kirill

2021-06-22 13:12 UTC, 4err requested changes

2021-06-22 13:12 UTC, 4err commented on js/form-validation.js
> +const NOBODY_GUEST_CAPACITY = '0';
Лучше сделать объект-словарь с данными. Так все параметры будут в одном объекте.

2021-06-22 13:12 UTC, 4err commented on js/form-validation.js
> +  else if (valueRoomNumber === FORTH_VALUE_ROOM_NUMBER) {
Лучше все-таки использовать цикл с перебором всех полей и значений. 
Обрати внимание, что количество посетителей всегда меньше или равно количеству комнат. Отталкиваясь от этого условия можно сделать цикл проверки.

2021-06-23 06:26 UTC, ks123kirill commented on js/form-validation.js
> +const NOBODY_GUEST_CAPACITY = '0';
OK. Переделал на словарь.

2021-06-24 05:31 UTC, 4err requested changes

2021-06-24 05:31 UTC, 4err commented on js/form-validation.js
> +  evt.target.value всегда равно 1 при выборе количества комнат. Почему?*/
Твоя функция `getDisabledCapacity` делает значение всех value в селекте равным 1 :) Оттого и эта проблема.
https://take.ms/gFoca

Проблема не в текущей функции, а в  `getDisabledCapacity`

2021-06-24 05:31 UTC, 4err commented on js/form-validation.js
> +    }
Два абсолютно одинаковых блока с разницей лишь в условии. Почему бы не объединить их в один if  с большим, сложным условием?

2021-06-24 05:31 UTC, 4err commented on js/form-validation.js
> +/* Функция устанавливает исходные настройки выбора: 1 room - 1 guest, выбор других опций количества guests заблокирован для 1 room. */
Данные могут измениться. Лучше отталкиваться от параметров `selected`. У тебя по умолчанию выбраны доступные варианты. Вот и оставь включенными только те, что сейчас `selected`.

2021-06-24 05:31 UTC, 4err commented on js/form-validation.js
> +};
А зачем вообще городить весь этот огород с функцией `getValueCapacityRoom ` если ты сразу можешь обратиться к объекту по ключу? 
Вместо `getValueCapacityRoom('1 guest')` использовать `itemList['1 guest']`. Даже писать короче :) Правда имя itemList лучше изменить на что-то более точное. 
Также не очень понятно зачем тебе прям все перечисления. Тебе же достаточно пограничных значений которые нужно обработать: 100 и 0. Остальные параметры неважны и по сути гостей может быть сколько угодно, как и комнат, это не должно увеличивать объем кода

2021-06-24 06:45 UTC, ks123kirill commented on js/form-validation.js
> +  evt.target.value всегда равно 1 при выборе количества комнат. Почему?*/
Ok. Поправил.

2021-06-24 06:53 UTC, ks123kirill commented on js/form-validation.js
> +    }
Согласен, сделал так что бы отсечь сразу значение "100". 
Объединил в один if со сложным условием, код стал почище.

2021-06-24 07:04 UTC, ks123kirill commented on js/form-validation.js
> +/* Функция устанавливает исходные настройки выбора: 1 room - 1 guest, выбор других опций количества guests заблокирован для 1 room. */
Согласен. Правильно. Переделал

2021-06-24 07:18 UTC, ks123kirill commented on js/form-validation.js
> +};
Согласен. Исправил.

2021-06-24 13:29 UTC, merged