Создал модуль активной и неактивной формы
htmlacademy-javascript/1530953-keksobooking-23 pull request #7
Opened 2021-06-22 11:57 UTC by ks123kirill

2021-06-22 13:06 UTC, 4err requested changes

2021-06-22 13:06 UTC, 4err commented on js/form-status.js
> +};
Кажется эти 2 функции очень похожи и по сути тут повторяется код. Почему бы не сделать одну функцию с параметром, которая будет включать или выключать форму.

2021-06-23 05:57 UTC, ks123kirill commented on js/form-status.js
> +};
ок. Переделал.

2021-06-23 07:03 UTC, 4err requested changes

2021-06-23 07:03 UTC, 4err commented on js/form-status.js
> +    }
Так все тоже самое дублирование кода, просто в одной функции :) Ты можешь использовать параметр в виде булева значения и присваивать его `adFormChildren[i].disabled` вот этим блокам. Если true, то оно выставит, если false то уберет. Тогда не придется дублировать циклы.

2021-06-23 13:34 UTC, ks123kirill commented on js/form-status.js
> +    }
Ок. Переделал.

2021-06-24 05:32 UTC, merged