Добавил валидацию тип жилья и время заезда
htmlacademy-javascript/1530953-keksobooking-23 pull request #9
Opened 2021-06-26 20:06 UTC by ks123kirill

2021-06-27 10:42 UTC, 4err requested changes

2021-06-27 10:42 UTC, 4err commented on js/form-validation.js
> +  'palace': '10000',
Лучше все-таки разделять списки. Плюс у тебя где-то должен быть перевод этих полей в русский вариант, вот лучше их там же указать.

2021-06-27 10:42 UTC, 4err commented on js/form-validation.js
> +      adTimeInList[i].selected = false;
У тебя же true и false присваиваются. Ты можешь заменить это выражение на присваивание условия:
` adTimeInList[i].selected = valueTimeOut === adTimeInList[i].value`
А еще можно не присваивать `selected` а просто задать селекту нужное значение и он выберет автоматически нужный пункт.

2021-06-28 05:48 UTC, ks123kirill commented on js/form-validation.js
> +  'palace': '10000',
Ок. Разделил списки. Список из другого модуля с переводом полей не использовал, потому что ключи одинаковые, значения разные.

2021-06-28 06:02 UTC, ks123kirill commented on js/form-validation.js
> +      adTimeInList[i].selected = false;
Ок. Заменил на присваивание условия. 
Не понял как сделать второй вариант про автоматический выбор нужного пункта.

2021-06-28 07:28 UTC, 4err requested changes

2021-06-28 07:28 UTC, 4err commented on js/form-validation.js
> +  'palace': '10000',
Так можно же сделать вложенный массив и иметь все параметры под рукой:
```
list = {
  flat: {
    price: 5000,
    name: "Квартира"        
  }
}
```

Что-то вроде такого

2021-06-28 08:34 UTC, ks123kirill commented on js/form-validation.js
> +  'palace': '10000',
Ок. Реализовал.

2021-06-28 09:38 UTC, merged